name 'supermarket-repo'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures supermarket-repo'
long_description 'Installs/Configures supermarket-repo'
version '0.1.0'
